### ISSUE TITLE
[BUG] Not working in headless

### ISSUE THREAD

**Issue by rushic24** [NeonGeckoCom/skill-alerts#111]
### Description

HI,

I'm unable to set any timer.

```
 Set a 1 minute timer                                                                                                                         
 >> Timer for one minute, starting now.                                                                                             --- 300.00
 >> An error occurred while processing a request in Alert Skill 
```

I believe it only works with GUI?
```
✗ docker-compose -f docker-compose.yml logs | grep timer

ovos_core        |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 247, in handle_create_timer
ovos_core        |     self._display_timer_gui(alert)
ovos_core        |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 760, in _display_timer_gui
ovos_core        |     self._update_homescreen(do_timers=True)
ovos_core        |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 247, in handle_create_timer
ovos_core        |     self._display_timer_gui(alert)
ovos_core        |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 760, in _display_timer_gui
ovos_core        |     self._update_homescreen(do_timers=True)
ovos_core        |   File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 247, in handle_create_timer
ovos_core        |     self._display_timer_gui(alert)
ovos_core        |   File "/home/ovos/.venv/lib/python3.11/si

```

Thanks

### Steps to Reproduce

Try asking  in ovos-cli-client

 Set a 1 minute timer  
 Set a 2 minute timer  
 Set a 10 second timer

**Comment by NeonDaniel** [comment]
It should still work without a GUI; the skill shouldn't care if there's a GUI attached or not.

It looks like the logs are cutoff here, can you provide logs including the full stack trace? I suspect the error is coming from `ovos_utils.gui`.

Also tagging @goldyfruit in case this is Docker-related since I presume you're using https://github.com/OpenVoiceOS/ovos-docker

**Comment by goldyfruit** [comment]
@rushic24 could you please provide the full trace?

**Comment by goldyfruit** [comment]
Installation went well.

```
Collecting git+https://github.com/NeonGeckoCom/skill-alerts.git (from -r /home/ovos/.config/mycroft/skills.list (line 2))
  Cloning https://github.com/NeonGeckoCom/skill-alerts.git to /tmp/pip-req-build-6y_280oa
  Running command git clone --filter=blob:none --quiet https://github.com/NeonGeckoCom/skill-alerts.git /tmp/pip-req-build-6y_280oa
  Resolved https://github.com/NeonGeckoCom/skill-alerts.git to commit 61007ea2563ea37ddf6468ca38090656af7bc1aa
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: python-dateutil in /home/ovos/.venv/lib/python3.11/site-packages (from skill-easter-eggs==0.0.1->-r /home/ovos/.config/mycroft/skills.list (line 1)) (2.8.2)
Requirement already satisfied: combo_lock~=0.2 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.2.5)
Requirement already satisfied: json_database~=0.5 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.7.0)
Collecting neon-utils~=1.2
  Downloading neon_utils-1.4.0-py3-none-any.whl (543 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 543.9/543.9 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: ovos-utils~=0.0.28 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.0.33a6)
Requirement already satisfied: filelock~=3.0 in /home/ovos/.venv/lib/python3.11/site-packages (from combo_lock~=0.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (3.12.0)
Requirement already satisfied: memory-tempfile in /home/ovos/.venv/lib/python3.11/site-packages (from combo_lock~=0.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.2.3)
Collecting mycroft-messagebus-client~=0.10
  Downloading mycroft_messagebus_client-0.10.1-py3-none-any.whl (23 kB)
Collecting pendulum~=2.1
  Downloading pendulum-2.1.2.tar.gz (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting timezonefinder~=5.2
  Downloading timezonefinder-5.2.0-py36.py37.py38-none-any.whl (43.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.0/43.0 MB 940.8 kB/s eta 0:00:00
Requirement already satisfied: nltk~=3.5 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (3.8.1)
Collecting pyyaml~=5.4
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: ovos-lingua-franca~=0.4 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.4.8a1)
Collecting geopy~=2.1
  Downloading geopy-2.3.0-py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: ovos-config~=0.0.7 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.0.9a1)
Requirement already satisfied: ovos-workshop~=0.0.10 in /home/ovos/.venv/lib/python3.11/site-packages (from neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.0.12a25)
Requirement already satisfied: kthread~=0.2 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.2.3)
Requirement already satisfied: pexpect~=4.8 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (4.8.0)
Requirement already satisfied: pyee in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (8.2.2)
Requirement already satisfied: requests~=2.26 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.30.0)
Requirement already satisfied: watchdog in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.3.1)
Requirement already satisfied: six>=1.5 in /home/ovos/.venv/lib/python3.11/site-packages (from python-dateutil->skill-easter-eggs==0.0.1->-r /home/ovos/.config/mycroft/skills.list (line 1)) (1.16.0)
Collecting geographiclib<3,>=1.52
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 1.3 MB/s eta 0:00:00
Collecting pyee
  Downloading pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: websocket-client>=0.54.0 in /home/ovos/.venv/lib/python3.11/site-packages (from mycroft-messagebus-client~=0.10->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (1.5.1)
Requirement already satisfied: click in /home/ovos/.venv/lib/python3.11/site-packages (from nltk~=3.5->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (8.1.3)
Requirement already satisfied: joblib in /home/ovos/.venv/lib/python3.11/site-packages (from nltk~=3.5->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /home/ovos/.venv/lib/python3.11/site-packages (from nltk~=3.5->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2023.5.5)
Requirement already satisfied: tqdm in /home/ovos/.venv/lib/python3.11/site-packages (from nltk~=3.5->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (4.65.0)
Requirement already satisfied: rich-click in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-config~=0.0.7->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (1.6.1)
Requirement already satisfied: rapidfuzz in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-lingua-franca~=0.4->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (3.0.0)
Requirement already satisfied: colour~=0.1 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-lingua-franca~=0.4->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.1.5)
Requirement already satisfied: webcolors in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-lingua-franca~=0.4->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (1.13)
Requirement already satisfied: quebra-frases in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-lingua-franca~=0.4->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.3.7)
Requirement already satisfied: ovos-bus-client<0.1.0,>=0.0.3 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-workshop~=0.0.10->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.0.4a9)
Requirement already satisfied: ovos-backend-client<0.1.0,>=0.0.6 in /home/ovos/.venv/lib/python3.11/site-packages (from ovos-workshop~=0.0.10->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.0.7a5)
Collecting pytzdata>=2020.1
  Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.0/490.0 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: ptyprocess>=0.5 in /home/ovos/.venv/lib/python3.11/site-packages (from pexpect~=4.8->ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.7.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ovos/.venv/lib/python3.11/site-packages (from requests~=2.26->ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/ovos/.venv/lib/python3.11/site-packages (from requests~=2.26->ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ovos/.venv/lib/python3.11/site-packages (from requests~=2.26->ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/ovos/.venv/lib/python3.11/site-packages (from requests~=2.26->ovos-utils~=0.0.28->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2022.12.7)
Collecting numpy>=1.16
  Downloading numpy-1.24.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 2.6 MB/s eta 0:00:00
Requirement already satisfied: rich>=10.7.0 in /home/ovos/.venv/lib/python3.11/site-packages (from rich-click->ovos-config~=0.0.7->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (13.3.5)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/ovos/.venv/lib/python3.11/site-packages (from rich>=10.7.0->rich-click->ovos-config~=0.0.7->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ovos/.venv/lib/python3.11/site-packages (from rich>=10.7.0->rich-click->ovos-config~=0.0.7->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /home/ovos/.venv/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.7.0->rich-click->ovos-config~=0.0.7->neon-utils~=1.2->neon-skill-alerts==1.5.0->-r /home/ovos/.config/mycroft/skills.list (line 2)) (0.1.2)
Building wheels for collected packages: pendulum, pyyaml
  Building wheel for pendulum (pyproject.toml): started
  Building wheel for pendulum (pyproject.toml): finished with status 'done'
  Created wheel for pendulum: filename=pendulum-2.1.2-cp311-cp311-manylinux_2_36_aarch64.whl size=109778 sha256=6904bbb0762e8a3e39483f55ae50da7f82d68e453928c78b8a77e3629860bd0f
  Stored in directory: /home/ovos/.cache/pip/wheels/a4/b7/10/a86f4f49b1bdf8a0cf3da42d48f499e4cb7529ebab7aad3550
  Building wheel for pyyaml (pyproject.toml): started
  Building wheel for pyyaml (pyproject.toml): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.4.1-cp311-cp311-linux_aarch64.whl size=45660 sha256=4f1d46775f205d2552391bfe5e78817485da718095697f8fd025b7a45e5cbbf3
  Stored in directory: /home/ovos/.cache/pip/wheels/2f/2f/af/a062a8f866dc44812a825da11175d50d7f255900f3b38c79b5
Successfully built pendulum pyyaml
Installing collected packages: pyee, pyyaml, pytzdata, numpy, mycroft-messagebus-client, geographiclib, timezonefinder, pendulum, geopy, neon-utils, neon-skill-alerts
  Attempting uninstall: pyee
    Found existing installation: pyee 8.2.2
    Uninstalling pyee-8.2.2:
      Successfully uninstalled pyee-8.2.2
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0
    Uninstalling PyYAML-6.0:
      Successfully uninstalled PyYAML-6.0
  DEPRECATION: neon-skill-alerts is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for neon-skill-alerts: started
  Running setup.py install for neon-skill-alerts: finished with status 'done'
Successfully installed geographiclib-2.0 geopy-2.3.0 mycroft-messagebus-client-0.10.1 neon-skill-alerts-1.5.0 neon-utils-1.4.0 numpy-1.24.3 pendulum-2.1.2 pyee-8.1.0 pytzdata-2020.1 pyyaml-5.4.1 timezonefinder-5.2.0
```

Skill loaded successfully.
```
2023-05-09 18:43:34.265 - skills - ovos_workshop.skill_launcher:_communicate_load_status:448 - INFO - Skill skill-alerts.neongeckocom loaded successfully
```

When I asked `set a one minute timer`, I got this trace:
```
[nltk_data] Downloading package punkt to /home/ovos/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ovos/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package universal_tagset to
[nltk_data]     /home/ovos/nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!
2023-05-09 18:44:02.210 - skills - ovos_core.transformers:transform:63 - DEBUG - ovos-utterance-coref-normalizer: {'client_name': 'ovos_dinkum_listener', 'destination': ['skills'], 'session': {'active_skills': [], 'context': {'frame_stack': [], 'timeout': 101020345140}, 'history': [[{'context': {}, 'data': {}, 'type': 'recognizer_loop:record_end'}, 1683672239.8341346]], 'lang': 'en-us', 'session_id': 'cf79f493-a5d1-4749-9de0-4e3953e94a69', 'utterance_states': {}, 'valid_languages': ['en-us']}, 'source': 'audio', 'transcription': 'set a one minute timer', 'utterances': ['set a one minute timer'], 'lang': 'en-us'}
2023-05-09 18:44:02.219 - skills - ovos_core.transformers:transform:63 - DEBUG - ovos-utterance-normalizer: {'client_name': 'ovos_dinkum_listener', 'destination': ['skills'], 'session': {'active_skills': [], 'context': {'frame_stack': [], 'timeout': 101020345140}, 'history': [[{'context': {}, 'data': {}, 'type': 'recognizer_loop:record_end'}, 1683672239.8341346]], 'lang': 'en-us', 'session_id': 'cf79f493-a5d1-4749-9de0-4e3953e94a69', 'utterance_states': {}, 'valid_languages': ['en-us']}, 'source': 'audio', 'transcription': 'set a one minute timer', 'utterances': ['set a one minute timer'], 'lang': 'en-us'}
2023-05-09 18:44:02.223 - skills - ovos_core.intent_services:_handle_transformers:172 - DEBUG - utterances transformed: ['set a one minute timer', 'set a one minute timer'] -> ['set a 1 minute timer', 'set a one minute timer']
2023-05-09 18:44:02.276 - skills - ovos_core.intent_services.padatious_service:_match_level:90 - DEBUG - Padatious Matching confidence > 0.95
2023-05-09 18:44:02.948 - skills - neon_utils.configuration_utils:get_config_dir:658 - DEBUG - /home/ovos/.config/neon
2023-05-09 18:44:02.958 - skills - neon_utils.configuration_utils:get_config_dir:660 - INFO - Creating config directory: /home/ovos/.config/neon
2023-05-09 18:44:03.055 - skills - ovos_config.models:load_local:105 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-05-09 18:44:03.061 - skills - neon_utils.configuration_utils:get_user_config_from_mycroft_conf:813 - DEBUG - Initializing mycroft config at /home/ovos/.config/mycroft/mycroft.conf
2023-05-09 18:44:03.089 - skills - ovos_utils.file_utils:resolve_resource_file:145 - WARNING - Expected a dict config and got None. This configfallback behavior will be deprecated in a future release
2023-05-09 18:44:03.164 - skills - neon_utils.skills.mycroft_skill:speak:161 - DEBUG - Skill speak! {'utterance': 'An error occurred while processing a request in Alert Skill', 'expect_response': False, 'meta': {'skill': 'AlertSkill'}, 'speaker': None, 'speak_ident': '1683672243.1487327'}
2023-05-09 18:44:03.179 - skills - neon_utils.skills.mycroft_skill:speak:162 - DEBUG - speak
2023-05-09 18:44:03.181 - skill-alerts.neongeckocom - ERROR - 'offset'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 554, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 238, in handle_create_timer
    tz = self._get_user_tz(message)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 1294, in _get_user_tz
    return gettz(self.location_timezone) if self.location_timezone else \
                                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 576, in location_timezone
    loc = self.location
          ^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/skills/mycroft_skill.py", line 65, in location
    return get_mycroft_compatible_location(get_user_prefs()["location"])
                                           ^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/message_utils.py", line 168, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/user_utils.py", line 83, in get_user_prefs
    default_user_config = get_default_user_config()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/user_utils.py", line 51, in get_default_user_config
    _DEFAULT_USER_CONFIG = get_user_config_from_mycroft_conf()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_utils/configuration_utils.py", line 834, in get_user_config_from_mycroft_conf
    "utc": str(round(mycroft_config["location"]["timezone"]["offset"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'offset'
```
Like it's looking for something in the configuration `mycroft_config["location"]["timezone"]["offset"]`.

**Comment by rushic24** [comment]
doesn't it use any default configuration?

**Comment by goldyfruit** [comment]
After adding the `offset` to my configuration, I got this trace:

```
2023-05-09 18:59:32.341 - skills - neon_utils.skills.mycroft_skill:speak:162 - DEBUG - speak
2023-05-09 18:59:32.345 - skill-alerts.neongeckocom - ERROR - 'Message' object has no attribute 'as_dict'
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 554, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 247, in handle_create_timer
    self.confirm_alert(alert, message, anchor_time)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 588, in confirm_alert
    self._display_timer_gui(alert)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 760, in _display_timer_gui
    self._update_homescreen(do_timers=True)
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_alerts/__init__.py", line 797, in _update_homescreen
    self.bus.emit(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/client/client.py", line 156, in emit
    sess.update_history(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_bus_client/session.py", line 121, in update_history
    m = message.as_dict
        ^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'as_dict'
```

**Comment by NeonDaniel** [comment]
Seems this arises from `ovos_bus_client` then.. `as_dict` isn't implemented in `mycroft-messagebus-client`, so I suspect this is related to the class patching that happens in ovos-bus-client

**Comment by JarbasAl** [comment]
`as_dict` and `from_dict` were introduced in the last ovos-bus-client

ovos-bus-client does not do any patching of other classes,

i did not account for message objects from mycroft-bus-client being passed to this lib, those 2 really should not coexist... the proper fix is to update imports to use ovos-bus-client directly, the hack we can do it in ovos-bus-client just to make migration easier is to cast back and forth to json instead of using the new methods.... 

this is not a use case i want to support long term,  one of the reasons that lib exists is that we needed to extend mycroft-bus-client and i want to be able to extend the Message object as needed (such as with the as_dict method which saved back and forth casting to json)

supporting mycroft Message objects in this ovos-bus-client is not an objective, the objective is that everyone uses ovos Message objects instead, but we can account for this edge case during 1 more minor version just to help the migration and LOG warnings

**Comment by JarbasAl** [comment]
fix https://github.com/OpenVoiceOS/ovos-bus-client/pull/26

**Comment by goldyfruit** [comment]
All good, skill is working with the fix.

**Comment by rushic24** [comment]
where can I use ovoid-bus-client in https://github.com/OpenVoiceOS/ovos-docker/ ?

**Comment by goldyfruit** [comment]
> where can I use ovoid-bus-client in https://github.com/OpenVoiceOS/ovos-docker/ ?

In `core`.

**Comment by rushic24** [comment]
It worked

```
docker exec -ti ovos_core bash
pip install --upgrade  git+https://github.com/OpenVoiceOS/ovos-bus-client.git@fix/mycroft_compat
exit
docker stop ovos_core
docker start ovos_core
```

**Comment by goldyfruit** [comment]
> It worked
> 
> ```
> docker exec -ti ovos_core bash
> pip install --upgrade  git+https://github.com/OpenVoiceOS/ovos-bus-client.git@fix/mycroft_compat
> exit
> docker stop ovos_core
> docker start ovos_core
> ```

Since @JarbasAl merged the PR into `core`, the new `ovos-core` image is built with the fix.

**Comment by goldyfruit** [comment]
The `alerts` skill is now part of the `ovos-docker` images.

https://github.com/OpenVoiceOS/ovos-docker/tree/dev/skills/skill-alerts
